### ISSUE TITLE
Hint matching

### ISSUE THREAD

**Issue by laerm0** [googlefonts/opensans#5] opened 2018-04-28 12:37 UTC
@davelab6 

@m4rc1e and I were talking about the plans to hint this and we won't be able to get total quality on ttfautohint with its defaults, so hinting it in Glyphs seems like best way; that is to say, export the fonts, have glyphs send them through ttfautohint, and then fix the ones that need fixing in Glyphs.

I am currently ensuring point compatibility between weights (hinting point compatibility is more strict than interpolation point compatibility) so that when we fix the glyphs that need better hinting, we only need to fix the regular weight and the hints will get applied to all masters.

**Comment by davelab6** [comment] 2018-07-11 02:32
> plans to hint this

I guess that the plan may have changed since April 28; what are the current plans to hint this, both as VF, and as static fonts? 

My guess is that we want to ship new static fonts that are hand hinted with no regressions but that solve the long standing problems with Open Sans, and then have a autohinted VF ready to be released when the VF API is completely solid. 

I agree that ttfautohint won't be acceptable; but I am also not sure that GlyphsApp can provide the same hinting as exists in the fonts in the API today - my impression is that GlyphsApp only does ClearType hinting, but the API fonts have ClearType, GreyScale and Black&White. 

> hinting point compatibility is more strict than interpolation point compatibility

I am curious why! :)

**Comment by davelab6** [comment] 2018-12-21 18:30
Closing as the plan ended up being VTT

**Closed by davelab6** 2018-12-21 18:30 UTC
